---
functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть способен обрабатывать большое количество трафика.
non-functional:
  - 
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
implicit:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  
#функциональные требования задают “что” система должна делать; нефункциональные – с соблюдением “каких условий”
